projects/github.com/sironheart/neovim-config:
  type: "git-repo"
  url: "git@github.com:Sironheart/neovim-config.git"

# .config/fish/conf.d/autopair.fish:
#   type: file
#   url: https://raw.githubusercontent.com/jorgebucaran/autopair.fish/refs/heads/main/conf.d/autopair.fish
#   refreshPeriod: 168h
