[settings]
experimental = true
disable_backends = ["ubi"]
pipx.uvx = true
python.uv_venv_auto = true
minimum_release_age = "7d"
lockfile = true

trusted_config_paths = ['~/projects']

[settings.github]
use_git_credentials = true

[tools]
go = "latest"
just = "latest"
lazygit = "latest"
rust = "latest"
node = "latest"
k9s = "latest"
atuin = "latest"
bat = "latest"
chezmoi = "latest"
eza = "latest"
fd = "latest"
gh = "latest"
helm = "latest"
kubectl = "latest"
neovim = "latest"
opencode = "latest"
oxfmt = "latest"
"1password-cli" = "latest"
ripgrep = "latest"
starship = "latest"
yq = "latest"
zoxide = "latest"

[tools."http:memini"]
version = "0.7.20"
checksum_url = 'https://git.erwanleboucher.dev/eleboucher/memini/releases/download/v{{version}}/memini_{{version}}_checksums.txt'
version_list_url = "https://git.erwanleboucher.dev/api/v1/repos/eleboucher/memini/releases"
version_json_path = ".[].tag_name"
version_order = "semver"

[tools."http:memini".platforms]
macos-arm64 = { url = 'https://git.erwanleboucher.dev/eleboucher/memini/releases/download/v{{version}}/memini_{{version}}_darwin_arm64.tar.gz' }
macos-x64 = { url = 'https://git.erwanleboucher.dev/eleboucher/memini/releases/download/v{{version}}/memini_{{version}}_darwin_amd64.tar.gz' }
linux-arm64 = { url = 'https://git.erwanleboucher.dev/eleboucher/memini/releases/download/v{{version}}/memini_{{version}}_linux_arm64.tar.gz' }
linux-x64 = { url = 'https://git.erwanleboucher.dev/eleboucher/memini/releases/download/v{{version}}/memini_{{version}}_linux_amd64.tar.gz' }
